name: SonarQube Scan

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run SonarQube scan
        env:
          SONAR_TOKEN: 988843c5b5ab30c1d2c2b1fac519977ac7f11e73
        run: |
          npx sonar-scanner \
            -Dsonar.organization=medreres \
            -Dsonar.projectKey=medreres_test-fp \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io
